version: "3.7"

services:
  mypharma_db:
    container_name: mypharma_db
    image: mongo:latest
    restart: always
    command: mongod --quiet --logpath /dev/null
    ports:
      - 27017:27017
    volumes:
      - ./database:/data/database
    environment:
      - MONGO_INITDB_DATABASE=MyPharma

  mypharma_api:
    container_name: mypharma_api
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server:/server/
    ports:
      - "3333:3333"
    depends_on:
      - mypharma_db

  mypharma_client:
    container_name: mypharma_client
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client:/client/
    ports:
      - "3000:3000"
    depends_on:
      - mypharma_api
