const productsMock = [
  {
    bar_code: "123456780",
    name: "Biotônico Fontoura",
    description: `Biotônico Fontoura é um suplemento de ferro utilizado para complementar a alimentação diária e estimular o apetite. Também auxilia na imunidade e energia, sem possuir açúcares.`,
    price: 25,
    quantity: 15,
    image: "biotonico.jpg",
  },
  {
    bar_code: "123456781",
    name: "Caixa de Chiclete",
    description: `O chiclete de uva da Marukawa proporciona uma experiência refrescante de sabor e diversão. Levemente azedinho, seu gosto agrada um grande número de pessoas, de todas as idades. Experimente e Compartilhe com seus amigos!`,
    price: 78,
    quantity: 50,
    image: "caixa-chiclete.jpg",
  },
  {
    bar_code: "123456782",
    name: "Desktop",
    description: `Projetado para fazer mais: Equipado com os processadores Intel® Core™ de 10ª geração e configurações com opções de armazenamento SSD, o Vostro Small Desktop tem tudo que você precisa para realizar suas tarefas com mais velocidade.`,
    price: 3249,
    quantity: 5,
    image: "desktop.jpg",
  },
  {
    bar_code: "123456783",
    name: "Desodorante Rexona",
    description: `• Nova Fórmula: 72 horas de proteção contra a transpiração e o mau odor, ativada pelo movimento.
    • O novo Rexona combina um inovador ativo antitranspirante com a exclusiva tecnologia de fragrância encapsulada. Te mantendo seco e protegido como nunca antes. Excluindo produtos Clinical. Vs antitranspirantes comuns em aerosol. `,
    price: 14.99,
    quantity: 100,
    image: "desodorante.jpg",
  },
  {
    bar_code: "123456784",
    name: "iPhone 12",
    description: `iPhone 12 Roxo, nova versão. Apenas para quem quer fazer a diferença`,
    price: 5799,
    quantity: 20,
    image: "iphone.jpg",
  },
  {
    bar_code: "123456785",
    name: "Loção CeraVe",
    description: `Desenvolvido com dermatologistas, CeraVe Loção Hidratante hidrata e ajuda a restaurar a barreira protetora da pele. Esta fórmula leve e não oleosa contém as 3 ceramidas essenciais para a pele e ácido hialurônico, promovendo hidratação o dia todo através de sua exclusiva tecnologia MVE, de liberação prolongada de ativos hidratantes. `,
    price: 80.9,
    quantity: 100,
    image: "locao.jpg",
  },
  {
    bar_code: "123456786",
    name: "MacBook M1",
    description: `O MacBook Pro de 13 polegadas está voando com toda a sua potência e velocidade do novo chip M1 da Apple. O desempenho da CPU ficou até 2,8 vezes melhor.`,
    price: 10999,
    quantity: 10,
    image: "macbook.jpg",
  },
  {
    bar_code: "123456787",
    name: "Perfumes",
    description: `Lancôme apresenta um novo caminho em um mundo repleto de regras e padrões: La Vie Est Belle - um perfume de alma e luz. La Vie Est Belle é um convite: escreva a sua própria história, encontre o seu caminho, faça a felicidade à sua maneira e sua vida se tornará muito mais bonita. `,
    price: 329,
    quantity: 50,
    image: "perfumes.jpg",
  },
  {
    bar_code: "123456788",
    name: "Remedios",
    description: `Remédios variados para tratar das mais diversas enfermidades, entre em contato com um médico e especialista e peça hoje mesmo!!`,
    price: 100,
    quantity: 50,
    image: "remedio.jpg",
  },
  {
    bar_code: "123456789",
    name: "Smartphone",
    description: `Smartphone Samsung Galaxy, com as melhores tecnologias da atualidade! Maior velocidade e desempenho para o seu melhor proveito.`,
    price: 4999,
    quantity: 5,
    image: "smartphone.jpg",
  },
  {
    bar_code: "1234567810",
    name: "Smartwatch",
    description: `Um produto muito legal feito para a garotada que ama práticar algum esporte, além de se comunicar com os amigos e estar sempre conectado.`,
    price: 4999,
    quantity: 50,
    image: "smartwatch.jpg",
  },
  {
    bar_code: "1234567812",
    name: 'Televisão 55"',
    description: `A Smart TV AOC Roku 43S5195/78 chegou para inovar o conceito de TVs inteligentes. A plataforma oferece um sistema de busca entre diversos aplicativos por ator, nome ou diretor do filme para uma experiência ainda melhor e facilitando na hora de encontrar o conteúdo desejado.`,
    price: 1899,
    quantity: 40,
    image: "televisao.jpg",
  },
  {
    bar_code: "1234567813",
    name: "Tenis",
    description: `Placa Infinity Wave: garante maior estabilidade, e também ajuda a dissipar a energia e amortecer cada passada. X10: Borracha de carbono que aumenta a durabilidade e oferece maior tração.`,
    price: 159.99,
    quantity: 20,
    image: "tenis.jpg",
  },
];

export default productsMock;
